powsybl/powsybl-ws-commons

- src/main/resources/application.yaml
> feat(application.yml): add index prefix conf

- src/main/resources/application.yaml
> Add a own powsybl-ws postgres database or Schema prefix parameter

- src/main/resources/application.yaml
> Add a own powsybl-ws cassandra keyspace prefix parameter

- src/main/resources/application.yaml
> Add forgotten 'powsybl-ws' yaml prefix when defining dbPrefix property

- pom.xml
Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
> Bump 1.1.0-SNAPSHOT

- pom.xml
> Prepare release v110

- src/main/resources/application.yaml
- src/main/resources/cassandra.properties
> Remove cassandra config

- pom.xml
Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
> Update PowSyBl version: core to 4.9.0 and parent to 8

- pom.xml
No
Release
1.2.0-SNAPSHOT
1.3.0-SNAPSHOT
> Prepare release 120

- src/main/resources/application.yaml
Signed-off-by: Abdelsalem <abdelsalem.hedhili@rte-france.com>
> increase max url length

- pom.xml
Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
No
Feature
PowSyBl 4.9.0
PowSyBl 4.10.1
(if any of the questions/checkboxes don't apply, please delete …
> Upgrade PowSyBl Core to 4.10.1

- pom.xml
No
Release
1.3.0-SNAPSHOT
1.4.0-SNAPSHOT
> Prepare release 1.3.0

- src/main/resources/application.yaml
Signed-off-by: TOURI ANIS <anis-1.touri@rte-france.com>
> Remove elasticsearch mock

- src/main/resources/application.yaml
https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.info.git-commit-information
NO
Feature
actuator/info:
```json
{
"git": {
"branch": "main",
"commit": {
"id": "4e9e4a3",
"time": "2023-01-20T13:52:28Z"
}
},
"build": {
"artifact": "gridsuite-study-server",
"name": "Study Server",
"time": …
```
> Add actuator/info full git (mainly for tags)

- pom.xml
> Migrate to powsybl-dependencies 2023.2.1

- pom.xml
> Bump to 1.5.0

- pom.xml
> Bump to 1.6.0-SNAPSHOT

- pom.xml
powsybl ws dependencies 2023.3.1
> powsybl dependencies 2023.3.1

- pom.xml
> release 1.6.0

- src/main/resources/application.yaml
> Docs: fix english readability instead of readiness

- pom.xml
> powsybl dependencies 2023.3.2

- pom.xml
> release 1.7.0

- pom.xml
> bump to v1.8.0-SNAPSHOT

- .gitignore
> Add gitignore rules for vscode

- pom.xml
> release 1.8.0

- pom.xml
> bump to v1.9.0-SNAPSHOT

- pom.xml
Dependency version upgrade
This upgrade was creating a version mismatch on junit which was failing tests. I used this PR to re-order the dependencies in the dependency management as it is more logical to make spring-boot prevalent on the technical dependencies.
> chore: upgrade to powsybl-dependencies 2024.0.3

- pom.xml
- src/main/java/com/powsybl/ws/commons/computation/service/ReportService.java
- src/test/java/com/powsybl/ws/commons/computation/service/ReportServiceTest.java
> Upgrade to powsybl dependencies 2024.2.0

- pom.xml
> Bump to 1.13-0-SNAPSHOT

- src/main/java/com/powsybl/ws/commons/computation/service/AbstractComputationService.java
- src/main/java/com/powsybl/ws/commons/computation/service/AbstractWorkerService.java
- src/main/java/com/powsybl/ws/commons/computation/service/CancelContext.java
- src/main/java/com/powsybl/ws/commons/computation/service/NotificationService.java
- src/test/java/com/powsybl/ws/commons/computation/ComputationTest.java
feature
if a computation couldn't be cancelled nothing is done
we send a message to inform that the computation couldn't be cancelled
> add output message if computation cancel failed

- pom.xml
> Bump to 1.14.0

- pom.xml
> Bump to 1.15.0-SNAPSHOT

- pom.xml
> Bump to 1.15.0

- pom.xml
> Bump to 1.16.0-SNAPSHOT

- src/main/java/com/powsybl/ws/commons/computation/service/AbstractWorkerService.java
> Default implementation for clean method in run

- pom.xml
> upgrade powsybl dependencies to v2024.3.1

- pom.xml
> release v1.16.0

- pom.xml
> bump to v1.17.0-SNAPSHOT

- pom.xml
> release v1.17.0

- pom.xml
> bump to v1.18.0-SNAPSHOT

- pom.xml
> Release v1.18.0

- pom.xml
> Bump to v1.19.0-SNAPSHOT

- pom.xml
> Release v1.19.0

- pom.xml
> Bump to v1.20.0-SNAPSHOT

- pom.xml
> Upgrade to powsybl dependencies 2024.4.0 and powsybl network store client 1.21.0

- pom.xml
> Bump to release 1.20.0

- pom.xml
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
> upgrade powsybl network store to v 1.22.0

- .github/workflows/maven.yml
- .github/workflows/patch.yml
- .github/workflows/release.yml
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
> add release and patch workflows

- pom.xml
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
> Upgrade powsybl network store version to 1.23.0

- src/main/java/com/powsybl/ws/commons/computation/service/AbstractWorkerService.java
> supervision: metrics on global computation

- pom.xml
> bump to v1.26.0-SNAPSHOT

- src/main/java/com/powsybl/ws/commons/computation/utils/ComputationResultUtils.java
- src/test/java/com/powsybl/ws/commons/computation/ComputationUtilTest.java
No
Bug fix
There is a violation location for all limit violations
There is a violation location for only voltage-based limit violations
None
> Fix location id for current limit violation

- pom.xml
> Release v1.25.1

- pom.xml
> bump to v1.27.0-SNAPSHOT

- src/main/java/com/powsybl/ws/commons/SecuredInputStream.java
- src/main/java/com/powsybl/ws/commons/SecuredTarInputStream.java
- src/main/java/com/powsybl/ws/commons/SecuredZipInputStream.java
No
Improve naming to make it clearer that maxSize is not the archive size but the uncompressed file sizes (cumulated) contained in the archive.
> Clarify max size

- src/main/java/com/powsybl/ws/commons/computation/utils/SpecificationUtils.java
- src/test/java/com/powsybl/ws/commons/computation/specification/CommonSpecificationBuilderTest.java
An IN specification containing too many possible values (around 7000) may cause a StackOverFlow.
IN specification which contains over 500 values are cut into chunks.
> max size on in specification
